export const styles = {
    main: {
        display: "flex",
        flexDirection: "column",
        padding: "0.5rem 0",
        width: "100%",
        backgroundColor: "#ECF1F3",
    },
    mainWholeItem: {
        display: "flex",
        justifyContent: "space-between",
        flexDirection: "row",
    },
    mainItemHeading: {
        fontSize: "0.8rem",
        fontWeight: "400",
        marginBottom: "0.5rem",
    },
    mainItemName: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "0.2rem 0",
        width: "14rem",
        maxWidth: "14rem",
    },
    mainItemNameBox: {
        display: "flex",
        width: "100%",
        alignItems: "center",
        borderRadius: "0.25rem",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "0.75rem",
        fontWeight: "400",
        textAlign: "left",
        padding: "0.2rem 0.5rem",
        height: "2rem",
        maxHeight: "4rem",
        overflow: "hidden",
    },
    mainItemNameBoxShort: {
        display: "flex",
        width: "100%",
        alignItems: "center",
        borderRadius: "0.25rem",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "0.75rem",
        fontWeight: "400",
        textAlign: "left",
        padding: "0.2rem 0.5rem",
        height: "2rem",
        maxHeight: "4rem",
        overflow: "hidden",
    },
    mainItemNameBoxLong: {
        display: "flex",
        width: "100%",
        alignItems: "center",
        borderRadius: "0.25rem",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "0.75rem",
        fontWeight: "400",
        textAlign: "left",
        padding: "0.2rem 0.5rem",
        height: "4rem",
        maxHeight: "4rem",
        overflow: "hidden",
    },
    mainItemUnit: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "0.2rem 0.5rem",
        width: "5rem",
        maxWidth: "5rem",
    },
    mainItemUnitBox: {
        display: "flex",
        alignItems: "center",
        borderRadius: "0.25rem",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "0.75rem",
        fontWeight: "400",
        width: "100%",
        height: "2rem",
        maxHeight: "2rem",
        padding: "0.2rem 0 0.2rem 0.5rem",
        justifyContent: "flex-start",
        textAlign: "left",
    },
    mainItemQty: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "0.2rem 0.5rem",
        width: "5.5rem",
        maxWidth: "5.5rem",
    },
    mainItemQtyBox: {
        display: "flex",
        alignItems: "center",
        borderRadius: "0.25rem",
        border: "none",
        background: "#FFF",
        color: "#3463AE",
        fontSize: "0.75rem",
        fontWeight: "400",
        height: "2rem",
        maxHeight: "2rem",
        padding: "0.2rem 0.5rem 0.2rem 0.2rem",
        justifyContent: "flex-end",
        textAlign: "right",
    },
    mainItemRate: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "0.2rem 0.5rem 0.2rem 0.2rem",
        width: "6rem",
        maxWidth: "6rem",
    },
    mainItemRateBox: {
        display: "flex",
        alignItems: "center",
        borderRadius: "0.25rem",
        border: "none",
        background: "#FFF",
        color: "#3463AE",
        fontSize: "0.75rem",
        fontWeight: "400",
        height: "2rem",
        maxHeight: "2rem",
        padding: "0.2rem 0.5rem 0.2rem 0",
        justifyContent: "flex-end",
        textAlign: "right",
    },
    mainItemDiscount: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "0.2rem 0 0.2rem 0.5rem",
        width: "7rem",
        maxWidth: "7rem",
    },
    mainItemDiscountBox: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        borderRadius: "0.25rem",
        border: "none",
        background: "#FFF",
        color: "#3463AE",
        fontSize: "0.75rem",
        fontWeight: "400",
        height: "2rem",
        maxHeight: "2rem",
        padding: "0",
    },
    mainItemDiscountAmount: {
        display: "flex",
        justifyContent: "flex-end",
        textAlign: "right",
        paddingRight: "0.5rem",
        width: "100%",
    },
    mainItemDiscountType: {
        height: "100%",
        width: "2rem",
        backgroundColor: "#ECF1F3",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "0 0.25rem 0.25rem 0",
        border: "1px solid #fff",
        color: "#3463AE",
        padding: "0 0.5rem",
    },
    mainItemTax: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "0.2rem 0.5rem",
        width: "7rem",
        maxWidth: "7rem",
    },
    mainItemTaxBox: {
        display: "flex",
        alignItems: "center",
        borderRadius: "0.25rem",
        border: "none",
        backgroundColor: "#ECF1F3",
        color: "#3463AE",
        fontSize: "0.75rem",
        fontWeight: "400",
        height: "2rem",
        maxHeight: "2rem",
        textAlign: "left",
        overflow: "hidden",
        width: "100%",
    },
    mainItemTaxAmount: {
        background: "#FFF",
        color: "black",
        fontSize: "0.75rem",
        fontWeight: "400",
        textAlign: "right",
        display: "flex",
        justifyContent: "flex-end",
        paddingRight: "0.5rem",
        alignItems: "center",
        height: "2rem",
        width: "100%",
    },
    mainItemTaxType: {
        width: "100%",
        maxWidth: "max-content",
        height: "100%",
        backgroundColor: "#ECF1F3",
        display: "flex",
        alignItems: "center",
        borderRadius: "0 0.25rem 0.25rem 0",
        border: "1px solid #fff",
        color: "#3463AE",
        padding: "0 0.5rem",
    },
    mainItemTaxTypeNS: {
        width: "100%",
        maxWidth: "100%",
        height: "100%",
        backgroundColor: "#ECF1F3",
        display: "flex",
        alignItems: "center",
        borderRadius: "0 0.25rem 0.25rem 0",
        border: "1px solid #fff",
        color: "#3463AE",
        padding: "0 0.5rem",
    },
    mainItemAmount: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "0.2rem 0.5rem 0.2rem 0.2rem",
        width: "7.5rem",
        maxWidth: "7.5rem",
    },
    mainItemAmountBox: {
        display: "flex",
        alignItems: "center",
        borderRadius: "0.25rem",
        border: "none",
        background: "#FFF",
        color: "#3463AE",
        fontSize: "0.75rem",
        fontWeight: "400",
        height: "2rem",
        maxHeight: "2rem",
        padding: "0.2rem 0.5rem 0.2rem 0.2rem",
        justifyContent: "flex-end",
        textAlign: "right",
    },
    mainItemDescription: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        width: "100%",
    },
    mainItemDescriptionBox: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "0.2rem 0.5rem 0.2rem 0",
    },
    mainItemDescriptionHeading: {
        fontSize: "0.75rem",
        fontWeight: "400",
        marginTop: "0.2rem",
    },
    mainItemDescriptionData: {
        fontSize: "0.75rem",
        fontWeight: "400",
        marginTop: "0.4rem",
        borderBottom: "1px dotted black",
        lineHeight: "1.5",
        width: "40%",
    },
}

export const pdfStyle = {
    main: {
        display: "flex",
        flexDirection: "column",
        padding: "3px 35px",
        width: "100%",
        backgroundColor: "#ECF1F3",
    },
    mainWholeItem: {
        display: "flex",
        flexDirection: "row",
    },
    mainItemHeading: {
        fontSize: "9px",
        fontWeight: "normal",
        marginBottom: "5px",
        overflow: "hidden",
    },
    mainItemName: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "3px 0",
        width: "160px",
        maxWidth: "160px",
    },
    mainItemNameBox: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderRadius: "2.5px",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "8px",
        fontWeight: "normal",
        textAlign: "left",
        padding: "2px 0 2px 5px",
        overflow: "hidden",
        maxHeight: "40px",
    },
    mainItemNameBoxShort: {
        height: "20px",
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderRadius: "2.5px",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "8px",
        fontWeight: "normal",
        textAlign: "left",
        padding: "2px 0 2px 5px",
        overflow: "hidden",
        maxHeight: "40px",
    },
    mainItemNameBoxLong: {
        height: "40px",
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderRadius: "2.5px",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "8px",
        fontWeight: "normal",
        textAlign: "left",
        padding: "2px 0 2px 5px",
        overflow: "hidden",
        maxHeight: "40px",
    },
    mainItemUnit: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "2px 0 2px 5px",
        width: "50px",
        maxWidth: "50px",
    },
    mainItemUnitBox: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderRadius: "2.5px",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "8px",
        fontWeight: "normal",
        height: "20px",
        maxHeight: "20px",
        padding: "2px 2px 2px 5px",
        justifyContent: "flex-start",
        textAlign: "left",
    },
    mainItemQty: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "2px 0 2px 5px",
        width: "60px",
        maxWidth: "60px",
    },
    mainItemQtyBox: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderRadius: "2.5px",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "8px",
        fontWeight: "normal",
        height: "20px",
        maxHeight: "20px",
        padding: "2px 5px 2px 2px",
        justifyContent: "flex-end",
        textAlign: "right",
    },
    mainItemRate: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "2px 0 2px 5px",
        width: "65px",
        maxWidth: "65px",
    },
    mainItemRateBox: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderRadius: "2.5px",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "8px",
        fontWeight: "normal",
        height: "20px",
        maxHeight: "20px",
        padding: "2px 5px 2px 2px",
        justifyContent: "flex-end",
        textAlign: "right",
    },
    mainItemDiscount: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "2px 0 2px 5px",
        width: "70px",
        maxWidth: "70px",
    },
    mainItemDiscountBox: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderRadius: "2.5px",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "8px",
        fontWeight: "normal",
        height: "20px",
        maxHeight: "20px",
        padding: "0",
    },
    mainItemDiscountAmount: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-end",
        textAlign: "right",
        paddingRight: "5px",
        width: "80%",
    },
    mainItemDiscountType: {
        height: "100%",
        backgroundColor: "#ECF1F3",
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        border: " 1px solid #fff",
        color: "#3463AE",
        padding: "0 5px 0 4px",
    },
    mainItemTax: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "2px 0 2px 5px",
        width: "70px",
        maxWidth: "70px",
    },
    mainItemTaxBox: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderRadius: "2.5px",
        border: "none",
        backgroundColor: "#ECF1F3",
        color: "#3463AE",
        fontSize: "8px",
        fontWeight: "normal",
        height: "20px",
        maxHeight: "20px",
        textAlign: "right",
        overflow: "hidden",
        width: "100%",
    },
    mainItemTaxAmount: {
        backgroundColor: "#FFF",
        color: "black",
        fontSize: "8px",
        fontWeight: "normal",
        textAlign: "right",
        display: "flex",
        justifyContent: "center",
        paddingRight: "5px",
        alignItems: "flex-end",
        height: "20px",
        padding: "0 5px",
        width: "100%",
    },
    mainItemTaxType: {
        width: "35px",
        height: "20px",
        maxHeight: "20px",
        backgroundColor: "#ECF1F3",
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        border: "1px solid #fff",
        color: "#3463AE",
        padding: "0 5px",
    },
    mainItemTaxTypeNS: {
        width: "100px",
        height: "20px",
        maxHeight: "20px",
        backgroundColor: "#ECF1F3",
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        border: "1px solid #fff",
        color: "#3463AE",
        padding: "0 5px",
    },
    mainItemAmount: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "2px 0 2px 5px",
        width: "70px",
        maxWidth: "70px",
    },
    mainItemAmountBox: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderRadius: "2.5px",
        border: "none",
        backgroundColor: "#FFF",
        color: "#3463AE",
        fontSize: "8px",
        fontWeight: "normal",
        height: "20px",
        maxHeight: "20px",
        padding: "2px 5px 2px 2px",
        justifyContent: "flex-end",
        textAlign: "right",
    },
    mainItemDescription: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        width: "100%",
    },
    mainItemDescriptionBox: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "2px 5px 2px 0",
    },
    mainItemDescriptionHeading: {
        fontSize: "8px",
        fontWeight: "normal",
        marginTop: "2px",
    },
    mainItemDescriptionData: {
        fontSize: "8px",
        fontWeight: "normal",
        marginTop: "4px",
        borderBottom: "1px dotted black",
        lineHeight: "1.5",
        width: "40%",
    },
}