export const styles = {
    main: {
        display: 'flex',
        flexDirection: 'row',
        width: '100%',
        padding: '1rem 4rem 0',
        gap: '0.8rem',
    },
    mainLeft: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        fontSize: '0.8rem',
        fontWeight: '300',
        lineHeight: '1.5',
        textAlign: 'left',
        width: '25%',
    },
    mainLeftHeading: {
        fontSize: '1.125rem',
        fontWeight: '500',
    },
    mainLeftData: {
        display: 'flex',
        flexDirection: 'column',
    },
    mainLeftCustomer: {
        fontWeight: '500',
    },
    mainMiddle: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        fontSize: '0.8rem',
        fontWeight: '300',
        lineHeight: '1.5',
        textAlign: 'left',
        width: '40%',
        gap: '0.4rem',
    },
    mainMiddleHeading: {
        fontSize: '1.125rem',
        fontWeight: '500',
    },
    mainMiddleData: {
        width: '90%',
        display: 'flex',
        flexDirection: 'column',
        border: '1px solid',
        borderColor: '#36BAA6',
        borderRadius: '8px',
    },
    mainMiddleDataHeading: {
        display: 'flex',
        justifyContent: 'space-between',
        fontWeight: '500',
        fontSize: '0.9rem',
        borderBottom: '1px solid',
        width: '100%',
        padding: '0.8rem',
        borderColor: '#36BAA6',
    },
    mainMiddleDataValue: {
        display: 'flex',
        flexDirection: 'column',
        fontWeight: '500',
        fontSize: '0.9rem',
        padding: '0.4rem 0.8rem',
        borderColor: '#36BAA6',
    },
    mainMiddleDataValueItem: {
        fontWeight: '300',
        display: 'flex',
        justifyContent: 'space-between',
        padding: '0.2rem 0',
    },
    mainRight: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        textAlign: 'left',
        width: '35%',
    },
    mainRightHeading1: {
        fontSize: '1rem',
        fontWeight: '500',
    },
    mainRightValue1: {
        color: '#3463AE',
        fontWeight: '700',
        padding: '0.3rem 0',
        fontSize: '1.5rem',
    },
    mainRightHeading2: {
        fontSize: '1rem',
        fontWeight: '500',
        marginTop: '1rem',
    },
    mainRightValue2: {
        color: '#3463AE',
        fontWeight: '700',
        padding: '0.3rem 0',
        fontSize: '1rem',
    },
}

export const pdfStyle = {
    main: {
        display: 'flex',
        flexDirection: 'row',
        width: '100%',
        gap: '40px',
        padding: '8px 40px 10px',
    },
    mainLeft: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        fontSize: '8px',
        fontWeight: 'normal',
        lineHeight: '1.5',
        textAlign: 'left',
        width: '25%',
    },
    mainLeftHeading: {
        fontSize: '12px',
        fontWeight: 'bold',
    },
    mainLeftData: {
        display: 'flex',
        flexDirection: 'column',
    },
    mainLeftCustomer: {
        fontWeight: 'bold',
    },
    mainMiddle: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        fontSize: '8px',
        fontWeight: 'normal',
        lineHeight: '1.5',
        textAlign: 'left',
        width: '40%',
        gap: '4px',
    },
    mainMiddleHeading: {
        fontSize: '12px',
        fontWeight: 'bold',
    },
    mainMiddleData: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: '#36BAA6',
        borderRadius: '8px',
    },
    mainMiddleDataHeading: {
        display: 'flex',
        justifyContent: 'space-between',
        fontWeight: 'normal',
        flexDirection: 'row',
        fontSize: '9px',
        borderBottomWidth: '1px',
        borderBottomStyle: 'solid',
        borderColor: '#36BAA6',
        width: '100%',
        padding: '8px 8px 4px',
    },
    mainMiddleDataValue: {
        display: 'flex',
        flexDirection: 'column',
        fontWeight: 'bold',
        fontSize: '9px',
        padding: '4px 0',
    },
    mainMiddleDataValueItem: {
        fontWeight: 'normal',
        display: 'flex',
        justifyContent: 'space-between',
        flexDirection: 'row',
        padding: '4px 8px 0',
    },
    mainRight: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        textAlign: 'left',
        width: '35%',
    },
    mainRightHeading1: {
        fontSize: '10px',
        fontWeight: 'bold',
    },
    mainRightValue1: {
        color: '#3463AE',
        fontWeight: 'bold',
        padding: '6px 0',
        fontSize: '15px',
    },
    mainRightHeading2: {
        fontSize: '10px',
        fontWeight: 'bold',
        marginTop: '15px',
    },
    mainRightValue2: {
        color: '#3463AE',
        fontWeight: 'bold',
        padding: '6px 0',
        fontSize: '10px',
    },
}