export const styles = {
    main: {
        display: 'flex',
        flexDirection: 'column',
        width: "100%",
        padding: "3rem 4rem",
    },
    tableHeader: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: "100%",
        padding: "0.5rem 1rem",
        backgroundColor: "#FAFAFA",
        borderRadius: "0.5rem 0.5rem 0 0",
        border: "1px solid #E0E0E0",
        borderBottom: "none",
    },
    tableHeaderCellLeft: {
        fontSize: "0.8rem",
        fontWeight: "500",
        textAlign: "left",
        width: "16%",
    },
    tableHeaderCellRight: {
        fontSize: "0.8rem",
        fontWeight: "500",
        textAlign: "right",
        width: "16%",
    },
    tableBody: {
        display: 'flex',
        flexDirection: 'column',
        width: "100%",
        padding: "0 1rem",
        borderRadius: "0 0 0.5rem 0.5rem",
        border: "1px solid #E0E0E0",
    },
    tableRow: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: "100%",
        padding: "0.5rem 0",
        borderBottom: "1px solid #E0E0E0",
    },
    tableRowCellLeft: {
        fontSize: "0.8rem",
        fontWeight: "400",
        textAlign: "left",
        width: "16%",
    },
    tableRowCellRight: {
        fontSize: "0.8rem",
        fontWeight: "400",
        textAlign: "right",
        width: "16%",
    },
}

export const pdfStyle = {
    main: {
        display: 'flex',
        flexDirection: 'column',
        width: "100%",
        padding: "8px 40px 10px",
    },
    tableHeader: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: "100%",
        padding: "8px 10px",
        backgroundColor: "#FAFAFA",
        borderWidth: "1px",
        borderStyle: "solid",
        borderColor: "#E0E0E0",
        borderBottom: "none",
        borderTopLeftRadius: "12px",
        borderTopRightRadius: "12px",
    },
    tableHeaderCellLeft: {
        fontSize: "8px",
        fontWeight: "bold",
        textAlign: "left",
        width: "16%",
    },
    tableHeaderCellRight: {
        fontSize: "8px",
        fontWeight: "bold",
        textAlign: "right",
        width: "16%",
    },
    tableBody: {
        display: 'flex',
        flexDirection: 'column',
        width: "100%",
        padding: "0 10px",
        borderWidth: "1px",
        borderStyle: "solid",
        borderColor: "#E0E0E0",
        borderBottomLeftRadius: "12px",
        borderBottomRightRadius: "12px",
    },
    tableRow: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: "100%",
        padding: "5px 0",
        borderBottomWidth: "1px",
        borderBottomStyle: "solid",
        borderBottomColor: "#E0E0E0",
    },
    tableRowCellLeft: {
        fontSize: "8px",
        fontWeight: "normal",
        textAlign: "left",
        width: "16%",
    },
    tableRowCellRight: {
        fontSize: "8px",
        fontWeight: "normal",
        textAlign: "right",
        width: "16%",
    },
}